<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:57
?>
<?php echo form_tag('level_preset/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($level_preset, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('level_preset[name]', __($labels['level_preset{name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('level_preset{name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('level_preset{name}')): ?>
    <?php echo form_error('level_preset{name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($level_preset, 'getName', array (
  'size' => 80,
  'control_name' => 'level_preset[name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('level_preset[department_id]', __($labels['level_preset{department_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('level_preset{department_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('level_preset{department_id}')): ?>
    <?php echo form_error('level_preset{department_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($level_preset, 'getDepartmentId', array (
  'related_class' => 'Department',
  'control_name' => 'level_preset[department_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('level_preset[grade_id]', __($labels['level_preset{grade_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('level_preset{grade_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('level_preset{grade_id}')): ?>
    <?php echo form_error('level_preset{grade_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($level_preset, 'getGradeId', array (
  'related_class' => 'Grade',
  'control_name' => 'level_preset[grade_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('level_preset[level]', __($labels['level_preset{level}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('level_preset{level}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('level_preset{level}')): ?>
    <?php echo form_error('level_preset{level}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($level_preset, 'getLevel', array (
  'size' => 7,
  'control_name' => 'level_preset[level]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('level_preset[question_no]', __($labels['level_preset{question_no}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('level_preset{question_no}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('level_preset{question_no}')): ?>
    <?php echo form_error('level_preset{question_no}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($level_preset, 'getQuestionNo', array (
  'size' => 7,
  'control_name' => 'level_preset[question_no]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('level_preset[created_at]', __($labels['level_preset{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('level_preset{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('level_preset{created_at}')): ?>
    <?php echo form_error('level_preset{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($level_preset, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'level_preset[created_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('level_preset' => $level_preset)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($level_preset->getId()): ?>
<?php echo button_to(__('delete'), 'level_preset/delete?id='.$level_preset->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
