<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:57
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('level_preset/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="name"><?php echo __('Type of Question:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[name]', isset($filters['name']) ? $filters['name'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="grade_id"><?php echo __('Grade:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['grade_id']) ? $filters['grade_id'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Grade',
  'text_method' => '__toString',
  'control_name' => 'filters[grade_id]',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="department_id"><?php echo __('Department:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['department_id']) ? $filters['department_id'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Department',
  'text_method' => '__toString',
  'control_name' => 'filters[department_id]',
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'level_preset/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
