<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:57
?>
    <td><?php echo link_to($level_preset->getId() ? $level_preset->getId() : __('-'), 'level_preset/edit?id='.$level_preset->getId()) ?></td>
    <td><?php echo $level_preset->getName() ?></td>
      <td><?php echo $level_preset->getDepartment() ?></td>
      <td><?php echo $level_preset->getGrade() ?></td>
      <td><?php echo $level_preset->getLevel() ?></td>
      <td><?php echo $level_preset->getQuestionNo() ?></td>
  