<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:57
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'level_preset/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
