<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:57
?>
<td colspan="6">
    <?php echo link_to($level_preset->getId() ? $level_preset->getId() : __('-'), 'level_preset/edit?id='.$level_preset->getId()) ?>
     - 
    <?php echo $level_preset->getName() ?>
     - 
    <?php echo $level_preset->getDepartment() ?>
     - 
    <?php echo $level_preset->getGrade() ?>
     - 
    <?php echo $level_preset->getLevel() ?>
     - 
    <?php echo $level_preset->getQuestionNo() ?>
     - 
</td>