<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2007/03/28 20:22:44
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
