<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2007/03/28 17:53:08

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://kra:kraSYSTEM@localhost/kra',
), 'propel');
$this->databases['propel'] = $database;
