<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 20:01:06
?>
<?php

/**
 * autoUser actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage autoUser
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id: actions.class.php 3501 2007-02-18 10:28:17Z fabien $
 */
class autoUserActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('user', 'list');
  }

  public function executeList()
  {
    $this->processSort();

    $this->processFilters();


    // pager
    $this->pager = new sfPropelPager('User', 20);
    $c = new Criteria();
    $this->addSortCriteria($c);
    $this->addFiltersCriteria($c);
    $this->pager->setCriteria($c);
    $this->pager->setPage($this->getRequestParameter('page', 1));
    $this->pager->init();
  }

  public function executeCreate()
  {
    return $this->forward('user', 'edit');
  }

  public function executeSave()
  {
    return $this->forward('user', 'edit');
  }

  public function executeEdit()
  {
    $this->user = $this->getUserOrCreate();

    if ($this->getRequest()->getMethod() == sfRequest::POST)
    {
      $this->updateUserFromRequest();

      $this->saveUser($this->user);

      $this->setFlash('notice', 'Your modifications have been saved');

      if ($this->getRequestParameter('save_and_add'))
      {
        return $this->redirect('user/create');
      }
      else if ($this->getRequestParameter('save_and_list'))
      {
        return $this->redirect('user/list');
      }
      else
      {
        return $this->redirect('user/edit?id='.$this->user->getId());
      }
    }
    else
    {
      $this->labels = $this->getLabels();
    }
  }

  public function executeDelete()
  {
    $this->user = UserPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->user);

    try
    {
      $this->deleteUser($this->user);
    }
    catch (PropelException $e)
    {
      $this->getRequest()->setError('delete', 'Could not delete the selected User. Make sure it does not have any associated items.');
      return $this->forward('user', 'list');
    }

    return $this->redirect('user/list');
  }

  public function handleErrorEdit()
  {
    $this->preExecute();
    $this->user = $this->getUserOrCreate();
    $this->updateUserFromRequest();

    $this->labels = $this->getLabels();

    return sfView::SUCCESS;
  }

  protected function saveUser($user)
  {
    $user->save();

  }

  protected function deleteUser($user)
  {
    $user->delete();
  }

  protected function updateUserFromRequest()
  {
    $user = $this->getRequestParameter('user');

    if (isset($user['fullname']))
    {
      $this->user->setFullname($user['fullname']);
    }
    if (isset($user['email']))
    {
      $this->user->setEmail($user['email']);
    }
    if (isset($user['username']))
    {
      $this->user->setUsername($user['username']);
    }
    if (isset($user['password']))
    {
      $this->user->setPassword($user['password']);
    }
    $this->user->setAdmin(isset($user['admin']) ? $user['admin'] : 0);
    if (isset($user['grade_id']))
    {
    $this->user->setGradeId($user['grade_id'] ? $user['grade_id'] : null);
    }
    if (isset($user['department_id']))
    {
    $this->user->setDepartmentId($user['department_id'] ? $user['department_id'] : null);
    }
    if (isset($user['created_at']))
    {
      if ($user['created_at'])
      {
        try
        {
          $dateFormat = new sfDateFormat($this->getUser()->getCulture());
                              if (!is_array($user['created_at']))
          {
            $value = $dateFormat->format($user['created_at'], 'I', $dateFormat->getInputPattern('g'));
          }
          else
          {
            $value_array = $user['created_at'];
            $value = $value_array['year'].'-'.$value_array['month'].'-'.$value_array['day'].(isset($value_array['hour']) ? ' '.$value_array['hour'].':'.$value_array['minute'].(isset($value_array['second']) ? ':'.$value_array['second'] : '') : '');
          }
          $this->user->setCreatedAt($value);
        }
        catch (sfException $e)
        {
          // not a date
        }
      }
      else
      {
        $this->user->setCreatedAt(null);
      }
    }
  }

  protected function getUserOrCreate($id = 'id')
  {
    if (!$this->getRequestParameter($id))
    {
      $user = new User();
    }
    else
    {
      $user = UserPeer::retrieveByPk($this->getRequestParameter($id));

      $this->forward404Unless($user);
    }

    return $user;
  }

  protected function processFilters()
  {
  }

  protected function processSort()
  {
    if ($this->getRequestParameter('sort'))
    {
      $this->getUser()->setAttribute('sort', $this->getRequestParameter('sort'), 'sf_admin/user/sort');
      $this->getUser()->setAttribute('type', $this->getRequestParameter('type', 'asc'), 'sf_admin/user/sort');
    }

    if (!$this->getUser()->getAttribute('sort', null, 'sf_admin/user/sort'))
    {
    }
  }

  protected function addFiltersCriteria($c)
  {
  }

  protected function addSortCriteria($c)
  {
    if ($sort_column = $this->getUser()->getAttribute('sort', null, 'sf_admin/user/sort'))
    {
      $sort_column = UserPeer::translateFieldName($sort_column, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_COLNAME);
      if ($this->getUser()->getAttribute('type', null, 'sf_admin/user/sort') == 'asc')
      {
        $c->addAscendingOrderByColumn($sort_column);
      }
      else
      {
        $c->addDescendingOrderByColumn($sort_column);
      }
    }
  }

  protected function getLabels()
  {
    return array(
      'user{id}' => 'Id:',
      'user{fullname}' => 'Fullname:',
      'user{email}' => 'Email:',
      'user{username}' => 'Username:',
      'user{password}' => 'Password:',
      'user{admin}' => 'Admin:',
      'user{grade_id}' => 'Grade:',
      'user{department_id}' => 'Department:',
      'user{created_at}' => 'Created at:',
    );
  }
}
