<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/13 21:28:18
?>
<?php echo form_tag('question/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($question, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('question[description]', __($labels['question{description}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('question{description}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('question{description}')): ?>
    <?php echo form_error('question{description}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($question, 'getDescription', array (
  'size' => '30x3',
  'control_name' => 'question[description]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('question[answer_a]', __($labels['question{answer_a}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('question{answer_a}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('question{answer_a}')): ?>
    <?php echo form_error('question{answer_a}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($question, 'getAnswerA', array (
  'size' => '30x3',
  'control_name' => 'question[answer_a]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('question[answer_b]', __($labels['question{answer_b}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('question{answer_b}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('question{answer_b}')): ?>
    <?php echo form_error('question{answer_b}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($question, 'getAnswerB', array (
  'size' => '30x3',
  'control_name' => 'question[answer_b]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('question[answer_c]', __($labels['question{answer_c}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('question{answer_c}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('question{answer_c}')): ?>
    <?php echo form_error('question{answer_c}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($question, 'getAnswerC', array (
  'size' => '30x3',
  'control_name' => 'question[answer_c]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('question[answer_d]', __($labels['question{answer_d}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('question{answer_d}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('question{answer_d}')): ?>
    <?php echo form_error('question{answer_d}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($question, 'getAnswerD', array (
  'size' => '30x3',
  'control_name' => 'question[answer_d]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('question[department_id]', __($labels['question{department_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('question{department_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('question{department_id}')): ?>
    <?php echo form_error('question{department_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($question, 'getDepartmentId', array (
  'related_class' => 'Department',
  'control_name' => 'question[department_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('question[level]', __($labels['question{level}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('question{level}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('question{level}')): ?>
    <?php echo form_error('question{level}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($question, 'getLevel', array (
  'size' => 7,
  'control_name' => 'question[level]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('question' => $question)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($question->getId()): ?>
<?php echo button_to(__('delete'), 'question/delete?id='.$question->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
