<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/13 21:28:18
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('question/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="department_id"><?php echo __('Type of Question:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['department_id']) ? $filters['department_id'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Department',
  'text_method' => '__toString',
  'control_name' => 'filters[department_id]',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="level"><?php echo __('Level:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[level]', isset($filters['level']) ? $filters['level'] : null, array (
  'size' => 7,
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'question/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
