<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/13 21:28:18
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'question/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
