<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/13 21:28:18
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Question Edit', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('question/edit_header', array('question' => $question)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('question/edit_messages', array('question' => $question, 'labels' => $labels)) ?>
<?php include_partial('question/edit_form', array('question' => $question, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('question/edit_footer', array('question' => $question)) ?>
</div>

</div>
