<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 17:43:07
?>
<td colspan="8">
    <?php echo link_to($user->getId() ? $user->getId() : __('-'), 'user/edit?id='.$user->getId()) ?>
     - 
    <?php echo $user->getFullname() ?>
     - 
    <?php echo $user->getEmail() ?>
     - 
    <?php echo $user->getUsername() ?>
     - 
    <?php echo $user->getPassword() ?>
     - 
    <?php echo $user->getAdmin() ? image_tag(sfConfig::get('sf_admin_web_dir').'/images/tick.png') : '&nbsp;' ?>
     - 
    <?php echo $user->getGrade() ?>
     - 
    <?php echo $user->getDepartment() ?>
     - 
</td>