<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 17:43:07
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'user/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
