<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 17:43:07
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/user/sort') == 'id'): ?>
      <?php echo link_to(__('id'), 'user/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('id'), 'user/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_fullname">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/user/sort') == 'fullname'): ?>
      <?php echo link_to(__('Fullname'), 'user/list?sort=fullname&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Fullname'), 'user/list?sort=fullname&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_email">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/user/sort') == 'email'): ?>
      <?php echo link_to(__('Email'), 'user/list?sort=email&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Email'), 'user/list?sort=email&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_username">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/user/sort') == 'username'): ?>
      <?php echo link_to(__('Username'), 'user/list?sort=username&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Username'), 'user/list?sort=username&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_password">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/user/sort') == 'password'): ?>
      <?php echo link_to(__('Password'), 'user/list?sort=password&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Password'), 'user/list?sort=password&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_admin">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/user/sort') == 'admin'): ?>
      <?php echo link_to(__('Admin'), 'user/list?sort=admin&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/user/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Admin'), 'user/list?sort=admin&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_grade">
        <?php echo __('Position Title') ?>
          </th>
  <th id="sf_admin_list_th_department">
        <?php echo __('Department') ?>
          </th>
