<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
    <td><?php echo link_to($department->getId() ? $department->getId() : __('-'), 'department/edit?id='.$department->getId()) ?></td>
    <td><?php echo $department->getName() ?></td>
      <td><?php echo $department->getUser() ?></td>
  