<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
<td colspan="3">
    <?php echo link_to($department->getId() ? $department->getId() : __('-'), 'department/edit?id='.$department->getId()) ?>
     - 
    <?php echo $department->getName() ?>
     - 
    <?php echo $department->getUser() ?>
     - 
</td>