<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit department', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('department/edit_header', array('department' => $department)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('department/edit_messages', array('department' => $department, 'labels' => $labels)) ?>
<?php include_partial('department/edit_form', array('department' => $department, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('department/edit_footer', array('department' => $department)) ?>
</div>

</div>
