<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:01:35
?>
<?php echo form_tag('answer_option/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($answer_option, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('answer_option[name]', __($labels['answer_option{name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('answer_option{name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('answer_option{name}')): ?>
    <?php echo form_error('answer_option{name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($answer_option, 'getName', array (
  'size' => 20,
  'control_name' => 'answer_option[name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('answer_option[option_name]', __($labels['answer_option{option_name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('answer_option{option_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('answer_option{option_name}')): ?>
    <?php echo form_error('answer_option{option_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($answer_option, 'getOptionName', array (
  'size' => 7,
  'control_name' => 'answer_option[option_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('answer_option' => $answer_option)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($answer_option->getId()): ?>
<?php echo button_to(__('delete'), 'answer_option/delete?id='.$answer_option->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
