<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:01:35
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/answer_option/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'answer_option/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/answer_option/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/answer_option/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'answer_option/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_name">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/answer_option/sort') == 'name'): ?>
      <?php echo link_to(__('Name'), 'answer_option/list?sort=name&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/answer_option/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/answer_option/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Name'), 'answer_option/list?sort=name&type=asc') ?>
      <?php endif; ?>
          </th>
