<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:01:35
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'answer_option/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
