<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:01:35
?>
<td colspan="2">
    <?php echo link_to($answer_option->getId() ? $answer_option->getId() : __('-'), 'answer_option/edit?id='.$answer_option->getId()) ?>
     - 
    <?php echo $answer_option->getName() ?>
     - 
</td>