<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:01:35
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit answer_option', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('answer_option/edit_header', array('answer_option' => $answer_option)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('answer_option/edit_messages', array('answer_option' => $answer_option, 'labels' => $labels)) ?>
<?php include_partial('answer_option/edit_form', array('answer_option' => $answer_option, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('answer_option/edit_footer', array('answer_option' => $answer_option)) ?>
</div>

</div>
