<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 20:01:06
?>
<?php echo form_tag('user/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($user, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('user[fullname]', __($labels['user{fullname}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('user{fullname}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{fullname}')): ?>
    <?php echo form_error('user{fullname}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($user, 'getFullname', array (
  'size' => 80,
  'control_name' => 'user[fullname]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('user[email]', __($labels['user{email}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('user{email}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{email}')): ?>
    <?php echo form_error('user{email}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($user, 'getEmail', array (
  'size' => 80,
  'control_name' => 'user[email]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('user[username]', __($labels['user{username}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('user{username}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{username}')): ?>
    <?php echo form_error('user{username}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($user, 'getUsername', array (
  'size' => 80,
  'control_name' => 'user[username]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('user[password]', __($labels['user{password}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('user{password}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{password}')): ?>
    <?php echo form_error('user{password}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($user, 'getPassword', array (
  'size' => 80,
  'control_name' => 'user[password]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('user[admin]', __($labels['user{admin}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('user{admin}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{admin}')): ?>
    <?php echo form_error('user{admin}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($user, 'getAdmin', array (
  'control_name' => 'user[admin]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('user[grade_id]', __($labels['user{grade_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('user{grade_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{grade_id}')): ?>
    <?php echo form_error('user{grade_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($user, 'getGradeId', array (
  'related_class' => 'Grade',
  'control_name' => 'user[grade_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('user[department_id]', __($labels['user{department_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('user{department_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{department_id}')): ?>
    <?php echo form_error('user{department_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($user, 'getDepartmentId', array (
  'related_class' => 'Department',
  'control_name' => 'user[department_id]',
  'include_custom' => 'Select Group',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('user[created_at]', __($labels['user{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('user{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('user{created_at}')): ?>
    <?php echo form_error('user{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($user, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'user[created_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('user' => $user)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($user->getId()): ?>
<?php echo button_to(__('delete'), 'user/delete?id='.$user->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
