<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/29 01:22:34
?>
<?php

/**
 * autoQuestion_generator actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage autoQuestion_generator
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id: actions.class.php 3501 2007-02-18 10:28:17Z fabien $
 */
class autoQuestion_generatorActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('question_generator', 'list');
  }

  public function executeList()
  {
    $this->processSort();

    $this->processFilters();


    // pager
    $this->pager = new sfPropelPager('QuestionGenerator', 20);
    $c = new Criteria();
    $this->addSortCriteria($c);
    $this->addFiltersCriteria($c);
    $this->pager->setCriteria($c);
    $this->pager->setPage($this->getRequestParameter('page', 1));
    $this->pager->init();
  }

  public function executeCreate()
  {
    return $this->forward('question_generator', 'edit');
  }

  public function executeSave()
  {
    return $this->forward('question_generator', 'edit');
  }

  public function executeEdit()
  {
    $this->question_generator = $this->getQuestionGeneratorOrCreate();

    if ($this->getRequest()->getMethod() == sfRequest::POST)
    {
      $this->updateQuestionGeneratorFromRequest();

      $this->saveQuestionGenerator($this->question_generator);

      $this->setFlash('notice', 'Your modifications have been saved');

      if ($this->getRequestParameter('save_and_add'))
      {
        return $this->redirect('question_generator/create');
      }
      else if ($this->getRequestParameter('save_and_list'))
      {
        return $this->redirect('question_generator/list');
      }
      else
      {
        return $this->redirect('question_generator/edit?id='.$this->question_generator->getId());
      }
    }
    else
    {
      $this->labels = $this->getLabels();
    }
  }

  public function executeDelete()
  {
    $this->question_generator = QuestionGeneratorPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->question_generator);

    try
    {
      $this->deleteQuestionGenerator($this->question_generator);
    }
    catch (PropelException $e)
    {
      $this->getRequest()->setError('delete', 'Could not delete the selected Question generator. Make sure it does not have any associated items.');
      return $this->forward('question_generator', 'list');
    }

    return $this->redirect('question_generator/list');
  }

  public function handleErrorEdit()
  {
    $this->preExecute();
    $this->question_generator = $this->getQuestionGeneratorOrCreate();
    $this->updateQuestionGeneratorFromRequest();

    $this->labels = $this->getLabels();

    return sfView::SUCCESS;
  }

  protected function saveQuestionGenerator($question_generator)
  {
    $question_generator->save();

  }

  protected function deleteQuestionGenerator($question_generator)
  {
    $question_generator->delete();
  }

  protected function updateQuestionGeneratorFromRequest()
  {
    $question_generator = $this->getRequestParameter('question_generator');

    if (isset($question_generator['user_id']))
    {
    $this->question_generator->setUserId($question_generator['user_id'] ? $question_generator['user_id'] : null);
    }
    if (isset($question_generator['question_id']))
    {
    $this->question_generator->setQuestionId($question_generator['question_id'] ? $question_generator['question_id'] : null);
    }
    if (isset($question_generator['answer']))
    {
      $this->question_generator->setAnswer($question_generator['answer']);
    }
    if (isset($question_generator['answer_option_id']))
    {
    $this->question_generator->setAnswerOptionId($question_generator['answer_option_id'] ? $question_generator['answer_option_id'] : null);
    }
    if (isset($question_generator['created_at']))
    {
      if ($question_generator['created_at'])
      {
        try
        {
          $dateFormat = new sfDateFormat($this->getUser()->getCulture());
                              if (!is_array($question_generator['created_at']))
          {
            $value = $dateFormat->format($question_generator['created_at'], 'I', $dateFormat->getInputPattern('g'));
          }
          else
          {
            $value_array = $question_generator['created_at'];
            $value = $value_array['year'].'-'.$value_array['month'].'-'.$value_array['day'].(isset($value_array['hour']) ? ' '.$value_array['hour'].':'.$value_array['minute'].(isset($value_array['second']) ? ':'.$value_array['second'] : '') : '');
          }
          $this->question_generator->setCreatedAt($value);
        }
        catch (sfException $e)
        {
          // not a date
        }
      }
      else
      {
        $this->question_generator->setCreatedAt(null);
      }
    }
    if (isset($question_generator['answer_at']))
    {
      if ($question_generator['answer_at'])
      {
        try
        {
          $dateFormat = new sfDateFormat($this->getUser()->getCulture());
                              if (!is_array($question_generator['answer_at']))
          {
            $value = $dateFormat->format($question_generator['answer_at'], 'I', $dateFormat->getInputPattern('g'));
          }
          else
          {
            $value_array = $question_generator['answer_at'];
            $value = $value_array['year'].'-'.$value_array['month'].'-'.$value_array['day'].(isset($value_array['hour']) ? ' '.$value_array['hour'].':'.$value_array['minute'].(isset($value_array['second']) ? ':'.$value_array['second'] : '') : '');
          }
          $this->question_generator->setAnswerAt($value);
        }
        catch (sfException $e)
        {
          // not a date
        }
      }
      else
      {
        $this->question_generator->setAnswerAt(null);
      }
    }
  }

  protected function getQuestionGeneratorOrCreate($id = 'id')
  {
    if (!$this->getRequestParameter($id))
    {
      $question_generator = new QuestionGenerator();
    }
    else
    {
      $question_generator = QuestionGeneratorPeer::retrieveByPk($this->getRequestParameter($id));

      $this->forward404Unless($question_generator);
    }

    return $question_generator;
  }

  protected function processFilters()
  {
  }

  protected function processSort()
  {
    if ($this->getRequestParameter('sort'))
    {
      $this->getUser()->setAttribute('sort', $this->getRequestParameter('sort'), 'sf_admin/question_generator/sort');
      $this->getUser()->setAttribute('type', $this->getRequestParameter('type', 'asc'), 'sf_admin/question_generator/sort');
    }

    if (!$this->getUser()->getAttribute('sort', null, 'sf_admin/question_generator/sort'))
    {
    }
  }

  protected function addFiltersCriteria($c)
  {
  }

  protected function addSortCriteria($c)
  {
    if ($sort_column = $this->getUser()->getAttribute('sort', null, 'sf_admin/question_generator/sort'))
    {
      $sort_column = QuestionGeneratorPeer::translateFieldName($sort_column, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_COLNAME);
      if ($this->getUser()->getAttribute('type', null, 'sf_admin/question_generator/sort') == 'asc')
      {
        $c->addAscendingOrderByColumn($sort_column);
      }
      else
      {
        $c->addDescendingOrderByColumn($sort_column);
      }
    }
  }

  protected function getLabels()
  {
    return array(
      'question_generator{id}' => 'Id:',
      'question_generator{user_id}' => 'User:',
      'question_generator{question_id}' => 'Question:',
      'question_generator{answer}' => 'Answer:',
      'question_generator{answer_option_id}' => 'Answer option:',
      'question_generator{created_at}' => 'Created at:',
      'question_generator{answer_at}' => 'Answer at:',
    );
  }
}
