<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/29 01:22:34
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'question_generator/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
