<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/29 01:22:34
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit question_generator', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('question_generator/edit_header', array('question_generator' => $question_generator)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('question_generator/edit_messages', array('question_generator' => $question_generator, 'labels' => $labels)) ?>
<?php include_partial('question_generator/edit_form', array('question_generator' => $question_generator, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('question_generator/edit_footer', array('question_generator' => $question_generator)) ?>
</div>

</div>
