<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
<?php echo form_tag('grade/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($grade, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('grade[name]', __($labels['grade{name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('grade{name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grade{name}')): ?>
    <?php echo form_error('grade{name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($grade, 'getName', array (
  'size' => 50,
  'control_name' => 'grade[name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('grade[description]', __($labels['grade{description}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('grade{description}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grade{description}')): ?>
    <?php echo form_error('grade{description}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($grade, 'getDescription', array (
  'size' => 80,
  'control_name' => 'grade[description]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('grade[department_id]', __($labels['grade{department_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grade{department_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grade{department_id}')): ?>
    <?php echo form_error('grade{department_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($grade, 'getDepartmentId', array (
  'related_class' => 'Department',
  'control_name' => 'grade[department_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('grade[created_at]', __($labels['grade{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grade{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grade{created_at}')): ?>
    <?php echo form_error('grade{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($grade, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'grade[created_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('grade' => $grade)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($grade->getId()): ?>
<?php echo button_to(__('delete'), 'grade/delete?id='.$grade->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
