<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
<td colspan="4">
    <?php echo link_to($grade->getId() ? $grade->getId() : __('-'), 'grade/edit?id='.$grade->getId()) ?>
     - 
    <?php echo $grade->getName() ?>
     - 
    <?php echo $grade->getDescription() ?>
     - 
    <?php echo $grade->getDepartment() ?>
     - 
</td>