<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grade/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'grade/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grade/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grade/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'grade/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_name">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grade/sort') == 'name'): ?>
      <?php echo link_to(__('Name'), 'grade/list?sort=name&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grade/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grade/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Name'), 'grade/list?sort=name&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_description">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grade/sort') == 'description'): ?>
      <?php echo link_to(__('Description'), 'grade/list?sort=description&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grade/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grade/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Description'), 'grade/list?sort=description&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_department">
        <?php echo __('Department') ?>
          </th>
