<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
    <td><?php echo link_to($grade->getId() ? $grade->getId() : __('-'), 'grade/edit?id='.$grade->getId()) ?></td>
    <td><?php echo $grade->getName() ?></td>
      <td><?php echo $grade->getDescription() ?></td>
      <td><?php echo $grade->getDepartment() ?></td>
  