<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 18:09:58
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit grade', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('grade/edit_header', array('grade' => $grade)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('grade/edit_messages', array('grade' => $grade, 'labels' => $labels)) ?>
<?php include_partial('grade/edit_form', array('grade' => $grade, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('grade/edit_footer', array('grade' => $grade)) ?>
</div>

</div>
